# Generated by Django 5.0.4 on 2024-04-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(max_length=225)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('saleprice', models.PositiveIntegerField(default=0)),
                ('purchaseprice', models.PositiveIntegerField(default=0)),
                ('stockbalance', models.IntegerField(default=0)),
                ('subitem', models.CharField(blank=True, max_length=255, null=True)),
                ('unpackqty', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
