# Generated by Django 5.0.4 on 2024-04-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_invoiceitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemname',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
