# Generated by Django 5.0.4 on 2024-04-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_item_itemname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='itemname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
